version: '3.8'

services:
  express-app:
    build:
      context: ./openweather-node
      dockerfile: docker/dockerfile  # Path to your Express app Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  quarkus-app:
    build:
      context: ./openweather-quarkus
      dockerfile: src/main/docker/Dockerfile.jvm  # Path to your Quarkus app Dockerfile
    environment:
      - OPENWEATHER_API_KEY=fill_your_api_key
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
